name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-earliest:
    name: Test on earliest supported Python
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        
    - name: Test
      run: |
        python run_tests.py
        
  test-latest:
    name: Test on latest known Python
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        
    - name: Test
      run: |
        python run_tests.py
        